name: data_requests
channels:
  - https://conda.anaconda.org/conda-forge/
  - conda-forge
dependencies:
  - annotated-types=0.6.0=pyhd8ed1ab_0
  - aws-c-auth=0.7.16=h7613915_8
  - aws-c-cal=0.6.10=hf6fcf4e_2
  - aws-c-common=0.9.14=hcfcfb64_0
  - aws-c-compression=0.2.18=hf6fcf4e_2
  - aws-c-event-stream=0.4.2=h3df98b0_6
  - aws-c-http=0.8.1=h4e3df0f_7
  - aws-c-io=0.14.6=hf0b8b6f_2
  - aws-c-mqtt=0.10.3=h96fac68_2
  - aws-c-s3=0.5.4=h08df315_0
  - aws-c-sdkutils=0.1.15=hf6fcf4e_2
  - aws-checksums=0.1.18=hf6fcf4e_2
  - aws-crt-cpp=0.26.4=hbe739fa_2
  - aws-sdk-cpp=1.11.267=hfaf0dd0_4
  - bokeh=3.4.0=pyhd8ed1ab_0
  - brotli-python=1.1.0=py310h00ffb61_1
  - bzip2=1.0.8=hcfcfb64_5
  - c-ares=1.27.0=hcfcfb64_0
  - ca-certificates=2024.2.2=h56e8100_0
  - click=8.1.7=win_pyh7428d3b_0
  - cloudpickle=3.0.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - contourpy=1.2.0=py310h232114e_0
  - cytoolz=0.12.3=py310h8d17308_0
  - dask=2024.3.1=pyhd8ed1ab_0
  - dask-core=2024.3.1=pyhd8ed1ab_0
  - dask-expr=1.0.5=pyhd8ed1ab_0
  - distributed=2024.3.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - freetype=2.12.1=hdaf720e_2
  - fsspec=2024.3.1=pyhca7485f_0
  - importlib-metadata=7.0.1=pyha770c72_0
  - importlib_metadata=7.0.1=hd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_0
  - intel-openmp=2024.0.0=h57928b3_49841
  - jinja2=3.1.3=pyhd8ed1ab_0
  - krb5=1.21.2=heb0366b_0
  - lcms2=2.16=h67d730c_0
  - lerc=4.0.0=h63175ca_0
  - libabseil=20240116.1=cxx17_h63175ca_2
  - libarrow=15.0.2=h878f99b_1_cpu
  - libarrow-acero=15.0.2=h63175ca_1_cpu
  - libarrow-dataset=15.0.2=h63175ca_1_cpu
  - libarrow-flight=15.0.2=h02312f3_1_cpu
  - libarrow-flight-sql=15.0.2=h55b4db4_1_cpu
  - libarrow-gandiva=15.0.2=h3f2ff47_1_cpu
  - libarrow-substrait=15.0.2=h89268de_1_cpu
  - libblas=3.9.0=21_win64_mkl
  - libbrotlicommon=1.1.0=hcfcfb64_1
  - libbrotlidec=1.1.0=hcfcfb64_1
  - libbrotlienc=1.1.0=hcfcfb64_1
  - libcblas=3.9.0=21_win64_mkl
  - libcrc32c=1.1.2=h0e60522_0
  - libcurl=8.7.1=hd5e4a3a_0
  - libdeflate=1.20=hcfcfb64_0
  - libevent=2.1.12=h3671451_1
  - libexpat=2.5.0=h63175ca_1
  - libffi=3.4.2=h8ffe710_5
  - libgoogle-cloud=2.22.0=h9cad5c0_1
  - libgoogle-cloud-storage=2.22.0=hb581fae_1
  - libgrpc=1.62.1=h5273850_0
  - libhwloc=2.9.3=default_haede6df_1009
  - libiconv=1.17=hcfcfb64_2
  - libjpeg-turbo=3.0.0=hcfcfb64_1
  - liblapack=3.9.0=21_win64_mkl
  - libparquet=15.0.2=h7ec3a38_1_cpu
  - libpng=1.6.43=h19919ed_0
  - libprotobuf=4.25.3=h503648d_0
  - libre2-11=2023.09.01=hf8d8778_2
  - libsqlite=3.45.1=hcfcfb64_0
  - libssh2=1.11.0=h7dfc565_0
  - libthrift=0.19.0=ha2b3283_1
  - libtiff=4.6.0=hddb2be6_3
  - libutf8proc=2.8.0=h82a8f57_0
  - libwebp-base=1.3.2=hcfcfb64_0
  - libxcb=1.15=hcd874cb_0
  - libxml2=2.12.5=hc3477c8_0
  - libzlib=1.2.13=hcfcfb64_5
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.3.3=py310hbbb2075_0
  - lz4-c=1.9.4=hcfcfb64_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=2.1.5=py310h8d17308_0
  - mkl=2024.0.0=h66d3029_49657
  - msgpack-python=1.0.7=py310h232114e_0
  - msys2-conda-epoch=20160418=1
  - numba=0.59.0=py310h9ccaf4f_1
  - numpy=1.24.4=py310hd02465a_0
  - openjpeg=2.5.2=h3d672ee_0
  - openssl=3.2.1=hcfcfb64_1
  - orc=2.0.0=heb0c069_0
  - packaging=23.2=pyhd8ed1ab_0
  - pandas=2.2.1=py310hecd3228_0
  - partd=1.4.1=pyhd8ed1ab_0
  - pillow=10.2.0=py310h1e6a543_0
  - pip=24.0=pyhd8ed1ab_0
  - pluggy=1.4.0=pyhd8ed1ab_0
  - psutil=5.9.8=py310h8d17308_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pthreads-win32=2.9.1=hfa6e2cd_3
  - pyarrow=15.0.2=py310hd0bb7c2_1_cpu
  - pyarrow-hotfix=0.6=pyhd8ed1ab_0
  - pydantic=2.6.3=pyhd8ed1ab_0
  - pydantic-core=2.16.3=py310h87d50f1_0
  - pyodbc=5.1.0=py310h00ffb61_0
  - pysocks=1.7.1=pyh0701188_6
  - pytest=8.0.2=pyhd8ed1ab_0
  - python=3.10.13=h4de0772_1_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.10=4_cp310
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.1=py310h8d17308_1
  - re2=2023.09.01=hd3b24a8_2
  - ruamel.yaml=0.18.6=py310h8d17308_0
  - ruamel.yaml.clib=0.2.8=py310h8d17308_0
  - scipy=1.12.0=py310hf667824_2
  - setuptools=69.1.1=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.10=hfb803bf_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - strictyaml=1.6.2=pyhd8ed1ab_0
  - tbb=2021.11.0=h91493d7_1
  - tblib=3.0.0=pyhd8ed1ab_0
  - tk=8.6.13=h5226925_1
  - tomli=2.0.1=pyhd8ed1ab_0
  - toolz=0.12.1=pyhd8ed1ab_0
  - tornado=6.4=py310h8d17308_0
  - typing-extensions=4.10.0=hd8ed1ab_0
  - typing_extensions=4.10.0=pyha770c72_0
  - tzdata=2024a=h0c530f3_0
  - ucrt=10.0.22621.0=h57928b3_0
  - urllib3=2.2.1=pyhd8ed1ab_0
  - vc=14.3=hcf57466_18
  - vc14_runtime=14.38.33130=h82b7239_18
  - versioningit=3.0.0=pyhd8ed1ab_0
  - vs2015_runtime=14.38.33130=hcb4865c_18
  - wheel=0.42.0=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyhd8ed1ab_6
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xyzservices=2023.10.1=pyhd8ed1ab_0
  - xz=5.2.6=h8d14728_0
  - yaml=0.2.5=h8ffe710_2
  - zict=3.0.0=pyhd8ed1ab_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zstd=1.5.5=h12be248_0
  - pip:
      - caf-toolkit==0.5.0
      - dnspython==2.6.1
      - llvmlite==0.42.0
      - mdbtools==0.3.14
      - pymongo==4.6.2
      - sparse==0.15.1
      - tqdm==4.66.2